from pydantic import BaseModel, Field
from typing import Dict, Any


class BusinessResponse(BaseModel):
    assistant_message: str = Field(..., description="The response text generated by the LLM.")
    goal_completed: bool = Field(..., description="Evaluated flag determining if process can advance.")
    extracted_data: Dict[str, Any] = Field(default_factory=dict, description="Parsed entity elements.")
    next_goal: str = Field(..., description="The target goal direction for the next turn loop.")
